name: add_remove_continuous_pressure
description: Add a widget that contains an increase button, a decrease button, and a widget that displays the value. You can increase or decrease the number by holding down or clicking once.
version: 1.0.1
repository: https://github.com/mustafa3max/add_remove_continuous_pressure

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
