name: add_remove_continuous_pressure
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/mustafa3max/add_remove_continuous_pressure

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
